#lang racket

(require serval/lib/unittest)

(provide (all-defined-out))

(define (jit-verify-case code proc)
  (test-case+ (format "VERIFY ~s" code) (proc code)))

(define (jit-skip-case code proc)
  (test-case+ (format "SKIP ~s" code) (void)))

(define-syntax (jit-verify stx)
  (syntax-case stx ()
    [(_ name proc selector code ...)
     (syntax/loc stx
       (run-tests (test-suite+ name
         ((selector code) code proc) ...)))]))

(define (verify-all code)
  jit-verify-case)

(define (skip-div+mod code)
  (if (or (member 'BPF_DIV code) (member 'BPF_MOD code))
      jit-skip-case
      jit-verify-case))

(define (verify-alu32-k name proc #:selector [selector verify-all])
  (jit-verify name proc selector
    '(BPF_ALU BPF_MOV BPF_K)
    '(BPF_ALU BPF_ADD BPF_K)
    '(BPF_ALU BPF_SUB BPF_K)
    '(BPF_ALU BPF_AND BPF_K)
    '(BPF_ALU BPF_OR BPF_K)
    '(BPF_ALU BPF_XOR BPF_K)
    '(BPF_ALU BPF_MUL BPF_K)
    '(BPF_ALU BPF_DIV BPF_K)
    '(BPF_ALU BPF_MOD BPF_K)
    '(BPF_ALU BPF_LSH BPF_K)
    '(BPF_ALU BPF_RSH BPF_K)
    '(BPF_ALU BPF_ARSH BPF_K)
))

(define (verify-alu32-x name proc #:selector [selector verify-all])
  (jit-verify name proc selector
    '(BPF_ALU BPF_MOV BPF_X)
    '(BPF_ALU BPF_ADD BPF_X)
    '(BPF_ALU BPF_SUB BPF_X)
    '(BPF_ALU BPF_AND BPF_X)
    '(BPF_ALU BPF_OR BPF_X)
    '(BPF_ALU BPF_XOR BPF_X)
    '(BPF_ALU BPF_MUL BPF_X)
    '(BPF_ALU BPF_DIV BPF_X)
    '(BPF_ALU BPF_MOD BPF_X)
    '(BPF_ALU BPF_LSH BPF_X)
    '(BPF_ALU BPF_RSH BPF_X)
    '(BPF_ALU BPF_ARSH BPF_X)
    '(BPF_ALU BPF_NEG)
))

(define (verify-alu64-k name proc #:selector [selector verify-all])
  (jit-verify name proc selector
    '(BPF_ALU64 BPF_MOV BPF_K)
    '(BPF_ALU64 BPF_ADD BPF_K)
    '(BPF_ALU64 BPF_SUB BPF_K)
    '(BPF_ALU64 BPF_AND BPF_K)
    '(BPF_ALU64 BPF_OR BPF_K)
    '(BPF_ALU64 BPF_XOR BPF_K)
    '(BPF_ALU64 BPF_MUL BPF_K)
    '(BPF_ALU64 BPF_DIV BPF_K)
    '(BPF_ALU64 BPF_MOD BPF_K)
    '(BPF_ALU64 BPF_LSH BPF_K)
    '(BPF_ALU64 BPF_RSH BPF_K)
    '(BPF_ALU64 BPF_ARSH BPF_K)
))

(define (verify-alu64-x name proc #:selector [selector verify-all])
  (jit-verify name proc selector
    '(BPF_ALU64 BPF_MOV BPF_X)
    '(BPF_ALU64 BPF_ADD BPF_X)
    '(BPF_ALU64 BPF_SUB BPF_X)
    '(BPF_ALU64 BPF_AND BPF_X)
    '(BPF_ALU64 BPF_OR BPF_X)
    '(BPF_ALU64 BPF_XOR BPF_X)
    '(BPF_ALU64 BPF_MUL BPF_X)
    '(BPF_ALU64 BPF_DIV BPF_X)
    '(BPF_ALU64 BPF_MOD BPF_X)
    '(BPF_ALU64 BPF_LSH BPF_X)
    '(BPF_ALU64 BPF_RSH BPF_X)
    '(BPF_ALU64 BPF_ARSH BPF_X)
    '(BPF_ALU64 BPF_NEG)
))

(define (verify-endian name proc #:selector [selector verify-all])
  (jit-verify name proc selector
    '(BPF_ALU BPF_END BPF_FROM_BE)
    '(BPF_ALU BPF_END BPF_FROM_LE)
))

(define (verify-jmp32-k name proc #:selector [selector verify-all])
  (jit-verify name proc selector
    '(BPF_JMP32 BPF_JEQ BPF_K)
    '(BPF_JMP32 BPF_JGT BPF_K)
    '(BPF_JMP32 BPF_JLT BPF_K)
    '(BPF_JMP32 BPF_JGE BPF_K)
    '(BPF_JMP32 BPF_JLE BPF_K)
    '(BPF_JMP32 BPF_JNE BPF_K)
    '(BPF_JMP32 BPF_JSGT BPF_K)
    '(BPF_JMP32 BPF_JSLT BPF_K)
    '(BPF_JMP32 BPF_JSGE BPF_K)
    '(BPF_JMP32 BPF_JSLE BPF_K)
    '(BPF_JMP32 BPF_JSET BPF_K)
))

(define (verify-jmp32-x name proc #:selector [selector verify-all])
  (jit-verify name proc selector
    '(BPF_JMP32 BPF_JEQ BPF_X)
    '(BPF_JMP32 BPF_JGT BPF_X)
    '(BPF_JMP32 BPF_JLT BPF_X)
    '(BPF_JMP32 BPF_JGE BPF_X)
    '(BPF_JMP32 BPF_JLE BPF_X)
    '(BPF_JMP32 BPF_JNE BPF_X)
    '(BPF_JMP32 BPF_JSGT BPF_X)
    '(BPF_JMP32 BPF_JSLT BPF_X)
    '(BPF_JMP32 BPF_JSGE BPF_X)
    '(BPF_JMP32 BPF_JSLE BPF_X)
    '(BPF_JMP32 BPF_JSET BPF_X)
))

(define (verify-jmp64-k name proc #:selector [selector verify-all])
  (jit-verify name proc selector
    '(BPF_JMP BPF_JA)
    '(BPF_JMP BPF_JEQ BPF_K)
    '(BPF_JMP BPF_JGT BPF_K)
    '(BPF_JMP BPF_JLT BPF_K)
    '(BPF_JMP BPF_JGE BPF_K)
    '(BPF_JMP BPF_JLE BPF_K)
    '(BPF_JMP BPF_JNE BPF_K)
    '(BPF_JMP BPF_JSGT BPF_K)
    '(BPF_JMP BPF_JSLT BPF_K)
    '(BPF_JMP BPF_JSGE BPF_K)
    '(BPF_JMP BPF_JSLE BPF_K)
    '(BPF_JMP BPF_JSET BPF_K)
))

(define (verify-jmp64-x name proc #:selector [selector verify-all])
  (jit-verify name proc selector
    '(BPF_JMP BPF_JEQ BPF_X)
    '(BPF_JMP BPF_JGT BPF_X)
    '(BPF_JMP BPF_JLT BPF_X)
    '(BPF_JMP BPF_JGE BPF_X)
    '(BPF_JMP BPF_JLE BPF_X)
    '(BPF_JMP BPF_JNE BPF_X)
    '(BPF_JMP BPF_JSGT BPF_X)
    '(BPF_JMP BPF_JSLT BPF_X)
    '(BPF_JMP BPF_JSGE BPF_X)
    '(BPF_JMP BPF_JSLE BPF_X)
    '(BPF_JMP BPF_JSET BPF_X)
))
